# Generated by Django 4.2.13 on 2024-07-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_marcamicroondas_alter_refrigeradora_costo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='televisor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
