# Generated by Django 4.2.13 on 2024-07-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_televisor_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisor',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
