# Generated by Django 4.2.13 on 2024-07-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_televisor_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='microondas',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refrigeradora',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
