# Generated by Django 4.2.13 on 2024-07-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_microondas_estado_refrigeradora_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='status',
        ),
        migrations.RemoveField(
            model_name='color',
            name='status',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='status',
        ),
        migrations.RemoveField(
            model_name='marcamicroondas',
            name='status',
        ),
        migrations.RemoveField(
            model_name='marcarefri',
            name='status',
        ),
        migrations.RemoveField(
            model_name='microondas',
            name='status',
        ),
        migrations.RemoveField(
            model_name='modelomicroondas',
            name='status',
        ),
        migrations.RemoveField(
            model_name='modelorefri',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='status',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='status',
        ),
        migrations.RemoveField(
            model_name='refrigeradora',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sexo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='televisor',
            name='status',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='status',
        ),
        migrations.AlterField(
            model_name='microondas',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Costo'),
        ),
    ]
