# Generated by Django 4.2.13 on 2024-07-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_ciudad_status_remove_color_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisor',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Costo'),
        ),
    ]
