# Generated by Django 4.2.13 on 2024-07-07 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_marca_options_resolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisor',
            name='resolucion',
            field=models.ForeignKey(blank=True, default='', max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.resolucion', verbose_name='Resolución'),
        ),
    ]
