# Generated by Django 4.2.13 on 2024-07-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_marca_options_alter_marcamicroondas_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refrigeradora',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
