# Generated by Django 4.2.13 on 2024-07-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_refrigeradora_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisor',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
