# Generated by Django 4.2.13 on 2024-07-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_televisor_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisor',
            name='stock',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='Stock'),
        ),
    ]
