# Generated by Django 4.2.13 on 2024-07-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_televisor_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisor',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Stock'),
        ),
    ]
