# Generated by Django 4.2.13 on 2024-07-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_televisor_stock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marca',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombreMarca',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Marca'),
        ),
    ]
