# Generated by Django 4.2.13 on 2024-07-07 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_marca_unique_together_alter_marca_nombremarca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='televisor',
            name='marca',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.marca', verbose_name='Marca'),
        ),
    ]
