# Generated by Django 4.2.13 on 2024-07-07 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_televisor_marca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sexo',
            options={'ordering': ['nombre'], 'verbose_name': 'Sexo', 'verbose_name_plural': 'Sexos'},
        ),
        migrations.AlterUniqueTogether(
            name='pais',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='sexo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.provincia', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='pais',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pais', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='sexo',
            name='nombre',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Sexo'),
        ),
    ]
