# Generated by Django 4.2.13 on 2024-07-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_marca_options_alter_marca_nombremarca_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['color'], 'verbose_name': 'Color', 'verbose_name_plural': 'Colores'},
        ),
        migrations.AlterModelOptions(
            name='marcamicroondas',
            options={'ordering': ['marcaMicroondas'], 'verbose_name': 'Marca de Microonda', 'verbose_name_plural': 'Marcas de Microonda'},
        ),
        migrations.AlterModelOptions(
            name='marcarefri',
            options={'ordering': ['marcaRefri'], 'verbose_name': 'Marca de Refri', 'verbose_name_plural': 'Marcas de Refri'},
        ),
        migrations.AlterModelOptions(
            name='modelomicroondas',
            options={'ordering': ['modelo'], 'verbose_name': 'Modelo de Microonda', 'verbose_name_plural': 'Modelo de Microondas'},
        ),
        migrations.AlterModelOptions(
            name='modelorefri',
            options={'ordering': ['modeloRefri'], 'verbose_name': 'Modelo de Refri', 'verbose_name_plural': 'Modelos de Refri'},
        ),
        migrations.AlterUniqueTogether(
            name='color',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='marcamicroondas',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='marcarefri',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='modelomicroondas',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='modelorefri',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='marcamicroondas',
            name='marcaMicroondas',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='marcarefri',
            name='marcaRefri',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='modelorefri',
            name='modeloRefri',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='resolucion',
            name='nombreResol',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Resolución'),
        ),
    ]
